#! /bin/bash
#Autor : ibrahim 
#Date : 9/8/2024
#Description : 	this script  will run basic task 
#Date modeified : 9/8/2024
echo
echo this script will run admin tasks 
echo 
top | head  -10
echo 
df -h 
echo 
uptime 
echo 
echo this is end of script

