#! /bin/bash
echo hello
echo
echo Enter the file name :
read file
if [ -f $file ] 
then 	
        if [ -x $file ]
        then
        echo file is executable
        else
	chmod +x $file	
	echo not  excutable but now is executable 	
        
        fi
else
echo file not exist ya bro
fi

echo
echo  End of script
