#! /bin/bash
#author : ibrahim 
#date : 9/8/2024
#desc : how to deal with inputs 
#modified time : 9/8/2024
echo  ########################## Star of script ################################################
echo
a='hostname'

echo Hello, my name is $($a)  
echo 
echo what  is your name ?
read name 
echo 
echo hello $name 
echo 
echo ######################## End of script #################################################
