#! /bin/bash
#author : ibrahim 
#date : 9/8/2024
#desc: how to use case statment 
#modified date : 
echo 
echo please choose one of option 
echo
echo 'a= display data and time'
echo 'b=list file and directory'
echo 'c=list users login '
echo 'd=check system uptime '
read choice 

case $choice in 
	a)   date ;;
	b)ls ;;
	c)who;;
	d)uptime;;
	*) echo  invalid coice ya bro 
		esac
